# Generated by Django 3.0.8 on 2020-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
